### ISSUE TITLE
mac/tcltk-wish.sh script no longer builds with Tcl/Tk 9

### ISSUE THREAD

**Issue by rnkn** [pure-data/pure-data#2519]
The `mac/tcltk-wish.sh` script no longer works with Tcl/Tk 9. It fails when building Tk. Here is the error:

```
sevastopol:~/Developer/pure-data/mac $ ./tcltk-wish.sh 9.0.1                                                                                                                     
[...]
	    /Users/rnkn/Developer/pure-data/mac/tk9.0.1/unix/../macosx/tkMacOSXInit.c
/Users/rnkn/Developer/pure-data/mac/tk9.0.1/unix/../macosx/tkMacOSXInit.c:491:5: error: Mac OS X 10.9 required
  491 | #   error Mac OS X 10.9 required
      |     ^
1 error generated.
make[3]: *** [tkMacOSXInit.o] Error 1
make[2]: *** [build-tk] Error 2
make[1]: *** [tk] Error 2
make: *** [embedded-deploy] Error 2
```

I'm running macOS 15.2, so well above 10.9.

I can quite easily build Tcl/Tk manually. I think it's just that `./configure` needs the `--with-tcl` path. 

But IMHO this script is a kludge and should be replaced entirely with a simple Makefile command to package the Pd.app from a Wish.app build the user does themselves (which shouldn't be hard if they're already building Pd themselves).

**Comment by umlaeute** [comment]
afaict, the problem is that the script is trying to build with `-mmacosx-version-min=10.6`

i was trying to tackle this on the day before yesterday on a macOS 10.12.6 "Sierra" VM, which is *also* too old build (iirc, it just fails a bit later than in your example).

i'll try to proceed in the next week.

**Comment by rnkn** [comment]
Yes I was wrong here:

> I think it's just that `./configure` needs the `--with-tcl` path.
